# Generated by Django 5.1.1 on 2026-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('measurement_unit', models.CharField(choices=[('GM', 'г'), ('KG', 'кг'), ('ML', 'мл'), ('LT', 'л'), ('IT', 'шт.'), ('TS', 'ст. л.'), ('TE', 'ч. л.'), ('LF', 'батон'), ('DR', 'капля'), ('JR', 'банка'), ('HF', 'горсть'), ('TW', 'веточка'), ('PN', 'щепотка'), ('GL', 'стакан'), ('PC', 'кусок'), ('TT', 'по вкусу')], default='GM', max_length=64, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
