volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data 
  
  frontend:
    container_name: foodgram-front
    image: dmitriygw/foodgram_frontend    
    volumes:
      - static:/static
  
  backend:
    container_name: foodgram-back
    image: dmitriygw/foodgram_backend
    env_file: ../.env    
    volumes:
      - static:/static
      - media:/media
        
  nginx:
    container_name: foodgram-proxy
    image: dmitriygw/foodgram_gateway
    ports:
      - "7000:80"
    volumes:      
      - static:/static
      - media:/media